### ISSUE TITLE
arduino nano esp32

### ISSUE THREAD

**Issue by docemiel** [Seeed-Studio/Grove_Sunlight_Sensor#11]
I have the si1151 sensor, and the arduino nano esp32 and the esp32 from espressif, the bild is not working!

In file included from C:\Users\João Bargão\AppData\Local\Temp\.arduinoIDE-unsaved2023828-3812-1uepz3i.11nl\sketch_sep28a\Si115X.h:5,
                 from C:\Users\João Bargão\AppData\Local\Temp\.arduinoIDE-unsaved2023828-3812-1uepz3i.11nl\sketch_sep28a\Si115X.cpp:2:
C:\Users\Jo�o Barg�o\AppData\Local\Arduino15\packages\arduino\hardware\esp32\2.0.13\libraries\Wire\src/Wire.h: In member function 'int Si115X::read_register(uint8_t, uint8_t, int)':
C:\Users\Jo�o Barg�o\AppData\Local\Arduino15\packages\arduino\hardware\esp32\2.0.13\libraries\Wire\src/Wire.h:127:13: note: candidate 1: 'uint8_t TwoWire::requestFrom(int, int)'
     uint8_t requestFrom(int address, int size);
             ^~~~~~~~~~~
C:\Users\Jo�o Barg�o\AppData\Local\Arduino15\packages\arduino\hardware\esp32\2.0.13\libraries\Wire\src/Wire.h:125:13: note: candidate 2: 'uint8_t TwoWire::requestFrom(uint8_t, uint8_t)'
     uint8_t requestFrom(uint8_t address, uint8_t size);
             ^~~~~~~~~~~
c:/users/jo�o barg�o/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32s3-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:\Users\Jo�o Barg�o\AppData\Local\Temp\arduino\sketches\7E17E364B33B454D5FB1A7EC3F438D36\sketch\sketch_sep28a.ino.cpp.o:(.literal._Z4loopv+0xc): undefined reference to `Si115X::ReadHalfWord()'
c:/users/jo�o barg�o/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32s3-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:\Users\Jo�o Barg�o\AppData\Local\Temp\arduino\sketches\7E17E364B33B454D5FB1A7EC3F438D36\sketch\sketch_sep28a.ino.cpp.o:(.literal._Z4loopv+0x10): undefined reference to `Si115X::ReadHalfWord_VISIBLE()'
c:/users/jo�o barg�o/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32s3-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:\Users\Jo�o Barg�o\AppData\Local\Temp\arduino\sketches\7E17E364B33B454D5FB1A7EC3F438D36\sketch\sketch_sep28a.ino.cpp.o:(.literal._Z4loopv+0x14): undefined reference to `Si115X::ReadHalfWord_UV()'
c:/users/jo�o barg�o/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32s3-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:\Users\Jo�o Barg�o\AppData\Local\Temp\arduino\sketches\7E17E364B33B454D5FB1A7EC3F438D36\sketch\sketch_sep28a.ino.cpp.o: in function `loop()':
C:\Users\João Bargão\AppData\Local\Temp\.arduinoIDE-unsaved2023828-3812-1uepz3i.11nl\sketch_sep28a/sketch_sep28a.ino:29: undefined reference to `Si115X::ReadHalfWord()'
c:/users/jo�o barg�o/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32s3-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:\Users\João Bargão\AppData\Local\Temp\.arduinoIDE-unsaved2023828-3812-1uepz3i.11nl\sketch_sep28a/sketch_sep28a.ino:30: undefined reference to `Si115X::ReadHalfWord_VISIBLE()'
c:/users/jo�o barg�o/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32s3-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:\Users\João Bargão\AppData\Local\Temp\.arduinoIDE-unsaved2023828-3812-1uepz3i.11nl\sketch_sep28a/sketch_sep28a.ino:31: undefined reference to `Si115X::ReadHalfWord_UV()'
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1

**Comment by ackPeng** [comment]
It seems that the library is not imported into the project correctly. Please check your library again. If you have any questions, please continue to communicate.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
