### ISSUE TITLE
Compilation error with library SI114X

### ISSUE THREAD

**Issue by baqwas** [Seeed-Studio/Grove_Sunlight_Sensor#2]
While trying to run the basic demo for the Grove _Sunlight Sensor_ using the library at this site, I encountered the following error message:

> collect2.exe: error: ld returned 5 exit status
> exit
> status  1
> Error

 compiling for board Arduino/Genuino Uno

If I comment out the **SI114X** library and corresponding code (see attachment) 
[testGroveBaseShield.zip](https://github.com/Seeed-Studio/Grove_Sunlight_Sensor/files/586526/testGroveBaseShield.zip)

then the file compiles and runs as expected. Unfortunately, just enabling the SI114X header file to be included in the code (while commenting out the rest of the **SI114X** related code), the error message persists. Is there an issue in supporting **SI114X** library under Arduino 1.6.11? **Thanks**.

**Comment by NavadeepGaneshU** [comment]
Hi, 
Did you find a resolution to this problem?
Looks like its because SI114X.h and .cpp were not pulled into Arduino libraries folder.

**Comment by baqwas** [comment]
Hello @NavadeepGaneshU,

I am no longer dependent on Grove libraries for my Arduino code to function properly.

Kind regards.
