### ISSUE TITLE
Sunlight Sensor V2

### ISSUE THREAD

**Issue by MKleinSB** [Seeed-Studio/Grove_Sunlight_Sensor#4]
Hello,
the sensor has upgrated to Si115
could you provide an updated Version? Or if possible an extension for makecode?

Thanks 

Michael

**Comment by lakshanthad** [comment]
Hello,

Is there any problem running with the current library?

Thank you.

**Comment by joernalraun** [comment]
Yes, the new sensor (SI115) requires an updated package that supports both versions if possible.

**Comment by lakshanthad** [comment]
Hello,

Please use this branch for Si115:
https://github.com/Seeed-Studio/Grove_Sunlight_Sensor/tree/Si1151

Thank you.
