### ISSUE TITLE
Not running on Xiao BLE

### ISSUE THREAD

**Issue by Kongduino** [Seeed-Studio/Grove_Sunlight_Sensor#7]
The library only creates a couple of commands for `TARGET_RP2040`. To add support for Xiao BLE, change:

```c
#if defined(TARGET_RP2040)
```

to:

```c
#if defined(TARGET_RP2040) || defined(_SEEED_XIAO_NRF52840_H_)
```

And after that the code will compile.

**Comment by mariaritafelici25** [comment]
Hi, I can't get Grove Sunlight Sensor to work with Xiao. Can you help me?

**Comment by docemiel** [comment]
and for the esp32 or arduino nano esp32? how i #if defined(????)

**Comment by ackPeng** [comment]
@mariaritafelici25 Can you describe the problem in more detail?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
