### ISSUE TITLE
Problem with Grove Sunlight & Seeed Xiao

### ISSUE THREAD

**Issue by mariaritafelici25** [Seeed-Studio/Grove_Sunlight_Sensor#9]
I can't get the Grove SunLight sensor to work with Seeed Xiao. Compilation fails. Can you help me? Thank you.

C:\Users\maria\AppData\Local\Temp\arduino\sketches\D2561346D8104EE7EEDC5A08CDE66AEA\sketch\XIAO_ProvaCanSat.ino.cpp.o: In function `loop':
C:\Users\maria\OneDrive\Documenti\Arduino\XIAO_ProvaCanSat/XIAO_ProvaCanSat.ino:46: undefined reference to `Si115X::ReadHalfWord()'
C:\Users\maria\OneDrive\Documenti\Arduino\XIAO_ProvaCanSat/XIAO_ProvaCanSat.ino:47: undefined reference to `Si115X::ReadHalfWord_VISIBLE()'
C:\Users\maria\OneDrive\Documenti\Arduino\XIAO_ProvaCanSat/XIAO_ProvaCanSat.ino:48: undefined reference to `Si115X::ReadHalfWord_UV()'
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1

**Comment by ackPeng** [comment]
It seems that the library is not imported correctly, so "undefined reference" appears.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
